collections:
  posts:
    permalink: /blog/:title

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-datapage-generator

defaults:
  - 
    scope:
      path: ""
      # type: "posts"
    values:
      author: sam
      # layout: default

#excerpt_separator: <!--more-->

page_gen_dirs: false
page_gen:
  - data: tags
    template: tag
    dir: tags
    name: name
    title_expr: |-
      record.fetch("displayname", record["name"])

timezone: America/Los_Angeles
