collections:
  posts:
    permalink: /blog/:title

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-datapage-generator
  - jekyll-github-metadata
  - jekyll-git-hash

defaults:
  - 
    scope:
      path: ""
      # type: "posts"
    values:
      author: hernies
      # layout: default
      commenting: closed

#excerpt_separator: <!--more-->

page_gen_dirs: false
page_gen:
  - data: tags
    template: tag
    dir: tags
    name: name
    title_expr: |-
      record.fetch("displayname", record["name"])

timezone: Europe/Madrid
url: https://hernies.net
title: hernies 
description: hernies 

emptyArray: []

# todo implement comments