collections:
  posts:
    permalink: /blog/:title

plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - 
    scope:
      path: ""
      # type: "posts"
    values:
      author: sam
      # layout: default

#excerpt_separator: <!--more-->
